console.log("My First Console Project");
var first_name="Siddharth ";
var last_name="Chikka";
console.log(first_name.concat(last_name));
var a = 13;
var b = 6;
var add = a + b;
console.log(add);
var subtract = a - b;
console.log(subtract);
var multiply = a * b;
console.log(multiply);
var divide = a / b;
console.log(divide);
